academic.out: academic.cpp
	g++ -static academic.cpp -o academic.out
run: academic.out
	./academic.out
clean:
#Custom Command
#deleting executables ending with .o extensions.
	rm -f academic.out *.o *~
